# -*- coding: utf-8 -*-
"""heart data csv

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BlqAwDsL5GkT8a2weWPjgG-EtZ0jctIt
"""

import pandas as pd

import seaborn as sns

import matplotlib.pyplot as plt

import numpy as np

df=pd.read_csv("/content/sample_data/heart.csv")

df.isnull().sum()

df.shape

df.describe()

df.columns

df.dtypes

from sklearn.preprocessing import LabelEncoder

label =LabelEncoder()

label

label.fit(df['RestingBP'])

label.classes_

label

encoder_for_heartdisease = LabelEncoder()
df['HeartDisease'] = encoder_for_heartdisease.fit_transform(df["HeartDisease"])

df['HeartDisease'].value_counts().plot(kind="bar")

df.columns

X = df.drop('HeartDisease',axis=1)
X

y=df['HeartDisease']

y

from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.20,random_state=2)

df.columns

X_train.shape

X_test.shape

X.shape

y_train.shape

y_test.shape

from sklearn.svm import SVC

svm_rbf=SVC(kernel='rbf')

categorical_cols = X_train.select_dtypes(include=['object']).columns

for col in categorical_cols:
    le = LabelEncoder()
    X_train[col] = le.fit_transform(X_train[col])
    X_test[col] = le.transform(X_test[col])

svm_rbf.fit(X_train, y_train)
svm_rbf.score(X_test, y_test) * 100

